version: '3'
services:
  database:
    image: "postgres"
    container_name: db-pg
    ports:
      - "6000:6000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: localhost
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata

  app:
    container_name: "app"
    image: app
    depends_on:
      - database
    env_file:
      - settings_server.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"