"""empty message

Revision ID: 5381e75c48cd
Revises: ba5a4b8da0ad
Create Date: 2024-03-09 10:49:28.277882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5381e75c48cd'
down_revision = 'ba5a4b8da0ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_organizations', sa.Column('start_range', sa.Integer(), nullable=False))
    op.add_column('type_organizations', sa.Column('end_range', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_organizations', 'end_range')
    op.drop_column('type_organizations', 'start_range')
    # ### end Alembic commands ###
