"""empty message

Revision ID: 7302c0eb57f7
Revises: 81c382edb21e
Create Date: 2024-03-13 11:39:07.410800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7302c0eb57f7'
down_revision = '81c382edb21e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('complexity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'complexity')
    # ### end Alembic commands ###
