"""empty message

Revision ID: 76fd66994fa9
Revises: da034ec21e2f
Create Date: 2024-03-10 20:15:13.920777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fd66994fa9'
down_revision = 'da034ec21e2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contest_id_state_contest_fkey', 'contest', type_='foreignkey')
    op.create_foreign_key(None, 'contest', 'state_contest', ['id_state_contest'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contest', type_='foreignkey')
    op.create_foreign_key('contest_id_state_contest_fkey', 'contest', 'type_contest', ['id_state_contest'], ['id'])
    # ### end Alembic commands ###
