"""empty message

Revision ID: cdf9d02f2747
Revises: 5381e75c48cd
Create Date: 2024-03-09 11:04:03.016754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf9d02f2747'
down_revision = '5381e75c48cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_edu_organization', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'educational_organizations', ['id_edu_organization'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'id_edu_organization')
    # ### end Alembic commands ###
