"""empty message

Revision ID: da034ec21e2f
Revises: 2066901a61ab
Create Date: 2024-03-10 19:59:41.721733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da034ec21e2f'
down_revision = '2066901a61ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_contest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_contest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contest', sa.Column('uuid', sa.UUID(), nullable=False))
    op.add_column('contest', sa.Column('id_type', sa.Integer(), nullable=True))
    op.add_column('contest', sa.Column('id_state_contest', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contest', 'type_contest', ['id_state_contest'], ['id'])
    op.create_foreign_key(None, 'contest', 'type_contest', ['id_type'], ['id'])
    op.drop_column('contest', 'state_contest')
    op.drop_column('contest', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contest', sa.Column('state_contest', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contest', type_='foreignkey')
    op.drop_constraint(None, 'contest', type_='foreignkey')
    op.drop_column('contest', 'id_state_contest')
    op.drop_column('contest', 'id_type')
    op.drop_column('contest', 'uuid')
    op.drop_table('type_contest')
    op.drop_table('state_contest')
    # ### end Alembic commands ###
