"""empty message

Revision ID: ec254b36148d
Revises: 3095f7c129b4
Create Date: 2024-03-14 12:06:58.383497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec254b36148d'
down_revision = '3095f7c129b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_registration')
    op.drop_table('team')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('team_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name_team', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='team_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('team_registration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_team', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_team'], ['team.id'], name='team_registration_id_team_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='team_registration_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='team_registration_pkey')
    )
    # ### end Alembic commands ###
