# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MainServer/Models/protos/answer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%MainServer/Models/protos/answer.proto\"\xdf\x01\n\x06\x41nswer\x12\x11\n\tdate_send\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x0f\n\x07id_team\x18\x03 \x01(\x03\x12\x0f\n\x07id_user\x18\x04 \x01(\x03\x12\x0f\n\x07id_task\x18\x05 \x01(\x03\x12\x12\n\nid_contest\x18\x06 \x01(\x03\x12\x18\n\x10name_compilation\x18\x08 \x01(\t\x12\r\n\x05total\x18\t \x01(\t\x12\x0c\n\x04time\x18\n \x01(\t\x12\x13\n\x0bmemory_size\x18\x0b \x01(\t\x12\x13\n\x0bnumber_test\x18\x0c \x01(\x05\x12\x0e\n\x06points\x18\r \x01(\x05\"\x85\x01\n\x11SendAnswerRequest\x12\x0f\n\x07id_task\x18\x01 \x01(\x03\x12\x0f\n\x07id_user\x18\x02 \x01(\x03\x12\x0f\n\x07id_team\x18\x03 \x01(\x03\x12\x12\n\nid_contest\x18\x04 \x01(\x03\x12\x13\n\x0bid_compiler\x18\x05 \x01(\x03\x12\x14\n\x0cprogram_file\x18\x06 \x01(\x0c\"&\n\x16SendAnswerCodeResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"N\n\x19GetListAnswersTaskRequest\x12\x14\n\x0ctype_contest\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x0f\n\x07id_task\x18\x03 \x01(\x03\"6\n\x1aGetListAnswersTaskResponse\x12\x18\n\x07\x61nswers\x18\x01 \x03(\x0b\x32\x07.Answer\":\n\x18GetAnswersContestRequest\x12\x12\n\nid_contest\x18\x01 \x01(\x03\x12\n\n\x02id\x18\x02 \x01(\x03\"5\n\x19GetAnswersContestResponse\x12\x18\n\x07\x61nswers\x18\x01 \x03(\x0b\x32\x07.Answer\")\n\x14GetReportFileRequest\x12\x11\n\tid_answer\x18\x01 \x01(\x03\",\n\x15GetReportFileResponse\x12\x13\n\x0breport_file\x18\x01 \x01(\x0c\x32\xab\x02\n\tAnswerApi\x12=\n\nSendAnswer\x12\x12.SendAnswerRequest\x1a\x17.SendAnswerCodeResponse\"\x00\x30\x01\x12O\n\x12GetListAnswersTask\x12\x1a.GetListAnswersTaskRequest\x1a\x1b.GetListAnswersTaskResponse\"\x00\x12L\n\x11GetAnswersContest\x12\x19.GetAnswersContestRequest\x1a\x1a.GetAnswersContestResponse\"\x00\x12@\n\rGetReportFile\x12\x15.GetReportFileRequest\x1a\x16.GetReportFileResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MainServer.Models.protos.answer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANSWER._serialized_start=42
  _ANSWER._serialized_end=265
  _SENDANSWERREQUEST._serialized_start=268
  _SENDANSWERREQUEST._serialized_end=401
  _SENDANSWERCODERESPONSE._serialized_start=403
  _SENDANSWERCODERESPONSE._serialized_end=441
  _GETLISTANSWERSTASKREQUEST._serialized_start=443
  _GETLISTANSWERSTASKREQUEST._serialized_end=521
  _GETLISTANSWERSTASKRESPONSE._serialized_start=523
  _GETLISTANSWERSTASKRESPONSE._serialized_end=577
  _GETANSWERSCONTESTREQUEST._serialized_start=579
  _GETANSWERSCONTESTREQUEST._serialized_end=637
  _GETANSWERSCONTESTRESPONSE._serialized_start=639
  _GETANSWERSCONTESTRESPONSE._serialized_end=692
  _GETREPORTFILEREQUEST._serialized_start=694
  _GETREPORTFILEREQUEST._serialized_end=735
  _GETREPORTFILERESPONSE._serialized_start=737
  _GETREPORTFILERESPONSE._serialized_end=781
  _ANSWERAPI._serialized_start=784
  _ANSWERAPI._serialized_end=1083
# @@protoc_insertion_point(module_scope)
