# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from MainServer.Services.protos import compiler_pb2 as MainServer_dot_Models_dot_protos_dot_compiler__pb2


class CompilerApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetListCompiler = channel.unary_unary(
                '/CompilerApi/GetListCompiler',
                request_serializer=MainServer_dot_Models_dot_protos_dot_compiler__pb2.GetListCompilerRequest.SerializeToString,
                response_deserializer=MainServer_dot_Models_dot_protos_dot_compiler__pb2.GetListCompilerResponse.FromString,
                )
        self.GetCompiler = channel.unary_unary(
                '/CompilerApi/GetCompiler',
                request_serializer=MainServer_dot_Models_dot_protos_dot_compiler__pb2.GetCompilerRequest.SerializeToString,
                response_deserializer=MainServer_dot_Models_dot_protos_dot_compiler__pb2.Compiler.FromString,
                )


class CompilerApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetListCompiler(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompiler(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompilerApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetListCompiler': grpc.unary_unary_rpc_method_handler(
                    servicer.GetListCompiler,
                    request_deserializer=MainServer_dot_Models_dot_protos_dot_compiler__pb2.GetListCompilerRequest.FromString,
                    response_serializer=MainServer_dot_Models_dot_protos_dot_compiler__pb2.GetListCompilerResponse.SerializeToString,
            ),
            'GetCompiler': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompiler,
                    request_deserializer=MainServer_dot_Models_dot_protos_dot_compiler__pb2.GetCompilerRequest.FromString,
                    response_serializer=MainServer_dot_Models_dot_protos_dot_compiler__pb2.Compiler.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CompilerApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CompilerApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetListCompiler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CompilerApi/GetListCompiler',
            MainServer_dot_Models_dot_protos_dot_compiler__pb2.GetListCompilerRequest.SerializeToString,
            MainServer_dot_Models_dot_protos_dot_compiler__pb2.GetListCompilerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCompiler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CompilerApi/GetCompiler',
            MainServer_dot_Models_dot_protos_dot_compiler__pb2.GetCompilerRequest.SerializeToString,
            MainServer_dot_Models_dot_protos_dot_compiler__pb2.Compiler.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
