# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from MainServer.Services.protos import contest_pb2 as MainServer_dot_Models_dot_protos_dot_contest__pb2


class ContestApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReportTotal = channel.unary_unary(
                '/ContestApi/GetReportTotal',
                request_serializer=MainServer_dot_Models_dot_protos_dot_contest__pb2.GetReportTotalRequest.SerializeToString,
                response_deserializer=MainServer_dot_Models_dot_protos_dot_contest__pb2.GetReportTotalResponse.FromString,
                )


class ContestApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetReportTotal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContestApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReportTotal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReportTotal,
                    request_deserializer=MainServer_dot_Models_dot_protos_dot_contest__pb2.GetReportTotalRequest.FromString,
                    response_serializer=MainServer_dot_Models_dot_protos_dot_contest__pb2.GetReportTotalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ContestApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContestApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetReportTotal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContestApi/GetReportTotal',
            MainServer_dot_Models_dot_protos_dot_contest__pb2.GetReportTotalRequest.SerializeToString,
            MainServer_dot_Models_dot_protos_dot_contest__pb2.GetReportTotalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
