# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MainServer/Models/protos/file.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#MainServer/Models/protos/file.proto\"\x1e\n\x0eStringResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"9\n\x08MetaData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x65xtend\x18\x02 \x01(\t\x12\x0f\n\x07id_task\x18\x03 \x01(\x03\"\x1e\n\x08\x46ileData\x12\x12\n\nbyte_chunk\x18\x01 \x01(\x0c\"X\n\x11UploadFileRequest\x12\x1d\n\x08metadata\x18\x01 \x01(\x0b\x32\t.MetaDataH\x00\x12\x19\n\x04\x66ile\x18\x02 \x01(\x0b\x32\t.FileDataH\x00\x42\t\n\x07request2l\n\x07\x46ileApi\x12\x35\n\nUploadFile\x12\x12.UploadFileRequest\x1a\x0f.StringResponse\"\x00(\x01\x12*\n\nDeleteFile\x12\t.MetaData\x1a\x0f.StringResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MainServer.Models.protos.file_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRINGRESPONSE._serialized_start=39
  _STRINGRESPONSE._serialized_end=69
  _METADATA._serialized_start=71
  _METADATA._serialized_end=128
  _FILEDATA._serialized_start=130
  _FILEDATA._serialized_end=160
  _UPLOADFILEREQUEST._serialized_start=162
  _UPLOADFILEREQUEST._serialized_end=250
  _FILEAPI._serialized_start=252
  _FILEAPI._serialized_end=360
# @@protoc_insertion_point(module_scope)
