# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from MainServer.Services.protos import file_pb2 as MainServer_dot_Models_dot_protos_dot_file__pb2


class FileApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.stream_unary(
                '/FileApi/UploadFile',
                request_serializer=MainServer_dot_Models_dot_protos_dot_file__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=MainServer_dot_Models_dot_protos_dot_file__pb2.StringResponse.FromString,
                )
        self.DeleteFile = channel.unary_unary(
                '/FileApi/DeleteFile',
                request_serializer=MainServer_dot_Models_dot_protos_dot_file__pb2.MetaData.SerializeToString,
                response_deserializer=MainServer_dot_Models_dot_protos_dot_file__pb2.StringResponse.FromString,
                )


class FileApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=MainServer_dot_Models_dot_protos_dot_file__pb2.UploadFileRequest.FromString,
                    response_serializer=MainServer_dot_Models_dot_protos_dot_file__pb2.StringResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=MainServer_dot_Models_dot_protos_dot_file__pb2.MetaData.FromString,
                    response_serializer=MainServer_dot_Models_dot_protos_dot_file__pb2.StringResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/FileApi/UploadFile',
            MainServer_dot_Models_dot_protos_dot_file__pb2.UploadFileRequest.SerializeToString,
            MainServer_dot_Models_dot_protos_dot_file__pb2.StringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileApi/DeleteFile',
            MainServer_dot_Models_dot_protos_dot_file__pb2.MetaData.SerializeToString,
            MainServer_dot_Models_dot_protos_dot_file__pb2.StringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
