# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MainServer/Models/protos/jsonTest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'MainServer/Models/protos/jsonTest.proto\"X\n\rSettingsTests\x12\x1b\n\x13limitation_variable\x18\x01 \x01(\t\x12\x16\n\x0enecessary_test\x18\x02 \x01(\t\x12\x12\n\ncheck_type\x18\x03 \x01(\t\"E\n\x05Tests\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x1d\n\x15\x66illing_type_variable\x18\x02 \x01(\x0c\x12\x0e\n\x06\x61nswer\x18\x03 \x01(\x0c\"J\n\nChunkTests\x12%\n\rsetting_tests\x18\x01 \x01(\x0b\x32\x0e.SettingsTests\x12\x15\n\x05tests\x18\x02 \x03(\x0b\x32\x06.Tests\"(\n\x1aGetAllSettingsTestsRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"?\n\x1bGetAllSettingsTestsResponse\x12 \n\x08settings\x18\x01 \x03(\x0b\x32\x0e.SettingsTests\"C\n\x13GetChunkTestRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\ttype_test\x18\x02 \x01(\t\x12\r\n\x05index\x18\x03 \x01(\x05\x32\x96\x01\n\x0bJsonTestApi\x12R\n\x13GetAllSettingsTests\x12\x1b.GetAllSettingsTestsRequest\x1a\x1c.GetAllSettingsTestsResponse\"\x00\x12\x33\n\x0cGetChunkTest\x12\x14.GetChunkTestRequest\x1a\x0b.ChunkTests\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MainServer.Models.protos.jsonTest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETTINGSTESTS._serialized_start=43
  _SETTINGSTESTS._serialized_end=131
  _TESTS._serialized_start=133
  _TESTS._serialized_end=202
  _CHUNKTESTS._serialized_start=204
  _CHUNKTESTS._serialized_end=278
  _GETALLSETTINGSTESTSREQUEST._serialized_start=280
  _GETALLSETTINGSTESTSREQUEST._serialized_end=320
  _GETALLSETTINGSTESTSRESPONSE._serialized_start=322
  _GETALLSETTINGSTESTSRESPONSE._serialized_end=385
  _GETCHUNKTESTREQUEST._serialized_start=387
  _GETCHUNKTESTREQUEST._serialized_end=454
  _JSONTESTAPI._serialized_start=457
  _JSONTESTAPI._serialized_end=607
# @@protoc_insertion_point(module_scope)
