# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from MainServer.Services.protos import settings_pb2 as MainServer_dot_Models_dot_protos_dot_settings__pb2


class SettingsApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SettingsPost = channel.unary_unary(
                '/SettingsApi/SettingsPost',
                request_serializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.Settings.SerializeToString,
                response_deserializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.CodeResponse.FromString,
                )
        self.SettingsGet = channel.unary_unary(
                '/SettingsApi/SettingsGet',
                request_serializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.GetSettingsRequest.SerializeToString,
                response_deserializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.GetSettingsResponse.FromString,
                )
        self.SettingsUpdate = channel.unary_unary(
                '/SettingsApi/SettingsUpdate',
                request_serializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.Settings.SerializeToString,
                response_deserializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.CodeResponse.FromString,
                )
        self.SettingsDelete = channel.unary_unary(
                '/SettingsApi/SettingsDelete',
                request_serializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.GetSettingsRequest.SerializeToString,
                response_deserializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.CodeResponse.FromString,
                )


class SettingsApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SettingsPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SettingsGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SettingsUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SettingsDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SettingsApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SettingsPost': grpc.unary_unary_rpc_method_handler(
                    servicer.SettingsPost,
                    request_deserializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.Settings.FromString,
                    response_serializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.CodeResponse.SerializeToString,
            ),
            'SettingsGet': grpc.unary_unary_rpc_method_handler(
                    servicer.SettingsGet,
                    request_deserializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.GetSettingsRequest.FromString,
                    response_serializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.GetSettingsResponse.SerializeToString,
            ),
            'SettingsUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SettingsUpdate,
                    request_deserializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.Settings.FromString,
                    response_serializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.CodeResponse.SerializeToString,
            ),
            'SettingsDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.SettingsDelete,
                    request_deserializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.GetSettingsRequest.FromString,
                    response_serializer=MainServer_dot_Models_dot_protos_dot_settings__pb2.CodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SettingsApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SettingsApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SettingsPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SettingsApi/SettingsPost',
            MainServer_dot_Models_dot_protos_dot_settings__pb2.Settings.SerializeToString,
            MainServer_dot_Models_dot_protos_dot_settings__pb2.CodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SettingsGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SettingsApi/SettingsGet',
            MainServer_dot_Models_dot_protos_dot_settings__pb2.GetSettingsRequest.SerializeToString,
            MainServer_dot_Models_dot_protos_dot_settings__pb2.GetSettingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SettingsUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SettingsApi/SettingsUpdate',
            MainServer_dot_Models_dot_protos_dot_settings__pb2.Settings.SerializeToString,
            MainServer_dot_Models_dot_protos_dot_settings__pb2.CodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SettingsDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SettingsApi/SettingsDelete',
            MainServer_dot_Models_dot_protos_dot_settings__pb2.GetSettingsRequest.SerializeToString,
            MainServer_dot_Models_dot_protos_dot_settings__pb2.CodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
