# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MainServer/Models/protos/settings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'MainServer/Models/protos/settings.proto\"\x1c\n\x0c\x43odeResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\x91\x01\n\x08Settings\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\ttime_work\x18\x02 \x01(\x05\x12\x10\n\x08size_raw\x18\x03 \x01(\x05\x12\x12\n\ntype_input\x18\x04 \x01(\x05\x12\x13\n\x0btype_output\x18\x06 \x01(\x05\x12\x18\n\x10number_shipments\x18\x05 \x01(\x05\x12\x11\n\tname_file\x18\x07 \x03(\t\" \n\x12GetSettingsRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"2\n\x13GetSettingsResponse\x12\x1b\n\x08settings\x18\x01 \x01(\x0b\x32\t.Settings2\xdb\x01\n\x0bSettingsApi\x12*\n\x0cSettingsPost\x12\t.Settings\x1a\r.CodeResponse\"\x00\x12:\n\x0bSettingsGet\x12\x13.GetSettingsRequest\x1a\x14.GetSettingsResponse\"\x00\x12,\n\x0eSettingsUpdate\x12\t.Settings\x1a\r.CodeResponse\"\x00\x12\x36\n\x0eSettingsDelete\x12\x13.GetSettingsRequest\x1a\r.CodeResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MainServer.Models.protos.settings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CODERESPONSE._serialized_start=43
  _CODERESPONSE._serialized_end=71
  _SETTINGS._serialized_start=74
  _SETTINGS._serialized_end=219
  _GETSETTINGSREQUEST._serialized_start=221
  _GETSETTINGSREQUEST._serialized_end=253
  _GETSETTINGSRESPONSE._serialized_start=255
  _GETSETTINGSRESPONSE._serialized_end=305
  _SETTINGSAPI._serialized_start=308
  _SETTINGSAPI._serialized_end=527
# @@protoc_insertion_point(module_scope)
